server:
  port: 8088
  servlet:
    session:
      cookie:
        name: ADMINSESSION
        http-only: true
        secure: true
        same-site: Lax

spring:
  application:
    name: onuljang
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
    timeout: 30m

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 200
    open-in-view: false

KAKAO:
  KEY: ${API_KAKAO_KEY:TODO}
  LOCAL_HOST: ${KAKAO_LOCAL_HOST:https://dapi.kakao.com}

KAKAOPAY:
  ENABLED: ${KAKAOPAY_ENABLED:false}
  ADMIN_KEY: ${KAKAOPAY_ADMIN_KEY:TODO}
  CID: ${KAKAOPAY_CID:TODO}
  APPROVAL_URL: ${KAKAOPAY_APPROVAL_URL:TODO}
  CANCEL_URL: ${KAKAOPAY_CANCEL_URL:TODO}
  FAIL_URL: ${KAKAOPAY_FAIL_URL:TODO}
  HOST: ${KAKAOPAY_HOST:https://kapi.kakao.com}


security:
  jwt:
    secret: ${JWT_SECRET}
    access-ttl-minutes: 30
    refresh-ttl-days: 7

cloud:
  aws:
    s3:
      bucket: ${S3_APP_BUCKET_NAME}
      log:
        bucket: ${S3_LOG_BUCKET_NAME}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

logging:
  level:
    org:
      springframework:
        security: DEBUG
