server:
  port: 8088
  servlet:
    session:
      cookie:
        name: ADMINSESSION
        http-only: true
        secure: true
        same-site: Lax

spring:
  application:
    name: onuljang
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
    timeout: 30m

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 200
    open-in-view: false

KAKAO:
  KEY: ${API_KAKAO_KEY}
  LOCAL_HOST: ${KAKAO_LOCAL_HOST:https://dapi.kakao.com}

KAKAOPAY:
  ENABLED: ${KAKAOPAY_ENABLED:false}
  SECRET_KEY: ${KAKAOPAY_SECRET_KEY}
  CID: ${KAKAOPAY_CID}
  APPROVAL_URL: ${KAKAOPAY_APPROVAL_URL}
  CANCEL_URL: ${KAKAOPAY_CANCEL_URL}
  FAIL_URL: ${KAKAOPAY_FAIL_URL}
  HOST: https://open-api.kakaopay.com
  COURIER_APPROVAL_URL: ${KAKAOPAY_COURIER_APPROVAL_URL:}
  COURIER_CANCEL_URL: ${KAKAOPAY_COURIER_CANCEL_URL:}
  COURIER_FAIL_URL: ${KAKAOPAY_COURIER_FAIL_URL:}

NAVERPAY:
  ENABLED: ${NAVERPAY_ENABLED:false}
  CLIENT_ID: ${NAVERPAY_CLIENT_ID:}
  CLIENT_SECRET: ${NAVERPAY_CLIENT_SECRET:}
  CHAIN_ID: ${NAVERPAY_CHAIN_ID:}
  HOST: ${NAVERPAY_HOST:https://dev.apis.naver.com}

TOSSPAY:
  ENABLED: ${TOSSPAY_ENABLED:false}
  SECRET_KEY: ${TOSSPAY_SECRET_KEY:}
  HOST: ${TOSSPAY_HOST:https://api.tosspayments.com}

security:
  jwt:
    secret: ${JWT_SECRET}
    access-ttl-minutes: 30
    refresh-ttl-days: 7

cloud:
  aws:
    s3:
      bucket: ${S3_APP_BUCKET_NAME}
      log:
        bucket: ${S3_LOG_BUCKET_NAME}
    sqs:
      base-url: https://sqs.${cloud.aws.region.static}.amazonaws.com/${cloud.aws.account-id}
      courier-tracking-request-queue-url: ${cloud.aws.sqs.base-url}/${SQS_COURIER_TRACKING_REQUEST_QUEUE_NAME:}
      courier-tracking-result-queue-url: ${cloud.aws.sqs.base-url}/${SQS_COURIER_TRACKING_RESULT_QUEUE_NAME:}
    account-id: ${AWS_ACCOUNT_ID:895428158418}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

cors:
  allowed-origins: http://localhost:3000

logging:
  level:
    org:
      springframework:
        security: DEBUG
